#UniveseMG Config

server_name: UniverseMG

# Is server in maintenance?
maintenance_mode: false

# Link to the server forums
forums: forumsgoeshere.boards.net

# Main server twitter handle
twitter: twittergoeshere

# Rank config
ranks:
  mafrans: MAINDEV
  sorryim2fresh: MAINDEV
  ethanyt: OWNER
 
filter:
  # Swear words to be filtered in /filter
  swearwords:
   - fuck
   - shit
   - penis
   - dick
   - hell
   - vagina
   - pussy

# TODO: Add more commands
commandblocker:
  # Vanilla commands
  /gamemode: ADMIN
  /give: ADMIN
  /kill: ADMIN
  # UMG commands
  /tag: HELPER
  # Essentials commands
  /i: ADMIN
  /gmc: ADMIN
  /gms: MODERATOR
  /gmsp: MODERATOR
  /fly: MODERATOR
  /sell: HELPER
  # Worldedit commands
  //*: ADMIN
  /br: ADMIN
  # BananaFun commands - http://github.com/Mafrans/BananaFun.git
  /slapfish: MODERATOR
  /instabow: HELPER
  /bouncer: HELPER
  /dynamite: ADMIN
  /woolbow: ADMIN
  /megaphone: ADMIN
  
  #DEV+ Commands
  /summon: DEV
  /sudo: DEV
  /pardon: DEV
  /entitydata: DEV
  /blockdata: DEV
  /setblock: DEV
  /fill: DEV
  /clone: DEV
  /op: DEV
  /enderdragon: MAINDEV
  /rl: DEV
  /stop: MAINDEV
  /restart: MAINDEV
  
  # Point Commands
  /nick: COINS:50
  
# Server list message.
motd:
  line0: '&b&m&l----&r&8&m&l[---&r &r&b&lUniverse&a&lMG &r&8&m&l---]&b&m&l----'
  line1: '&r&a%staffcount% &bStaff Online'

tablist:
  header:
   - '&b&m&l----&r&8&m&l[---&r &r&b&lUniverse&a&lMG &r&8&m&l---]&b&m&l----'
   - '&a%playercount% &bPlayers Online'
  footer:
   - '&bJoin our Forum at &a%forum%'

# Default ban reason
default-ban-reason: 'The ban hammer has spoken!'

overlord-ips:
 - 127.0.0.1
 - 89.160.85.9
 

# Server HTTPD
httpd:
    enabled: true
    port: 80