#UniveseMG Config

# Is server in maintenance?
maintenance_mode: false

# Link to the server forums
forums: forumsgoeshere.boards.net

# Rank config
ranks:
  mafrans: MAINDEV
  sorryim2fresh: MAINDEV
  ethanyt: OWNER
  
filter:
  swearwords:
   - fuck
   - shit
   - penis
   - dick
   - hell
   - vagina
   - pussy

# TODO: Add more commands
commandblocker:
  # Vanilla commands
  /gamemode: ADMIN
  /give: ADMIN
  /kill: ADMIN
  # Essentials commands
  /i: ADMIN
  /gmc: ADMIN
  /gms: MODERATOR
  /gmsp: MODERATOR
  /fly: MODERATOR
  /sell: HELPER
  # Worldedit commands
  //*: ADMIN
  /br: ADMIN
  # BananaFun commands - http://github.com/Mafrans/BananaFun.git
  /slapfish: MODERATOR
  /instabow: HELPER
  /bouncer: HELPER
  /dynamite: ADMIN
  /woolbow: ADMIN
  /megaphone: ADMIN
  
  
  #DEV+ Commands
  /summon: DEV
  /sudo: DEV
  /pardon: DEV
  /entitydata: DEV
  /blockdata: DEV
  /setblock: DEV
  /fill: DEV
  /clone: DEV
  /op: DEV
  /enderdragon: MAINDEV
  /rl: DEV
  /stop: MAINDEV
  /restart: MAINDEV
  
  
overlord-ips:
 - 127.0.0.1
 - 89.160.85.9